const PRESETS = [
  {
    name: 'Windows Desktop',
    platform: 'Win32',
    uaPlatformToken: 'Windows NT 10.0; Win64; x64',
    clientHintsPlatform: 'Windows',
    platformVersion: '15.0.0',
    arch: 'x86',
    bitness: '64',
    maxTouchPoints: 0,
    taskbarHeight: 40,
    dpr: 1,
    chromeVersions: [
      '132.0.6834.110',
      '131.0.6778.205',
      '130.0.6723.117',
      '133.0.6943.54',
      '134.0.7025.40',
    ],
    hardwareConcurrency: [4, 8, 12, 16],
    deviceMemory: [4, 8, 16],
    screenResolutions: [
      [1920, 1080],
      [2560, 1440],
      [1366, 768],
      [1536, 864],
      [1440, 900],
    ],
    gpus: [
      { vendor: 'Google Inc. (NVIDIA)', renderer: 'ANGLE (NVIDIA, NVIDIA GeForce RTX 3060 Direct3D11 vs_5_0 ps_5_0, D3D11)' },
      { vendor: 'Google Inc. (NVIDIA)', renderer: 'ANGLE (NVIDIA, NVIDIA GeForce GTX 1660 SUPER Direct3D11 vs_5_0 ps_5_0, D3D11)' },
      { vendor: 'Google Inc. (AMD)', renderer: 'ANGLE (AMD, AMD Radeon RX 580 Direct3D11 vs_5_0 ps_5_0, D3D11)' },
      { vendor: 'Google Inc. (Intel)', renderer: 'ANGLE (Intel, Intel(R) UHD Graphics 630 Direct3D11 vs_5_0 ps_5_0, D3D11)' },
      { vendor: 'Google Inc. (NVIDIA)', renderer: 'ANGLE (NVIDIA, NVIDIA GeForce RTX 4060 Direct3D11 vs_5_0 ps_5_0, D3D11)' },
    ],
    languages: [
      { primary: 'zh-CN', list: ['zh-CN', 'zh', 'en-US', 'en'], accept: 'zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7' },
      { primary: 'en-US', list: ['en-US', 'en'], accept: 'en-US,en;q=0.9' },
      { primary: 'ja', list: ['ja', 'en-US', 'en'], accept: 'ja,en-US;q=0.9,en;q=0.8' },
    ],
    timezones: [
      { name: 'Asia/Shanghai', offset: -480 },
      { name: 'America/New_York', offset: 300 },
      { name: 'Europe/London', offset: 0 },
      { name: 'Asia/Tokyo', offset: -540 },
    ],
    fonts: [
      'Arial', 'Arial Black', 'Calibri', 'Cambria', 'Comic Sans MS',
      'Consolas', 'Courier New', 'Georgia', 'Impact', 'Lucida Console',
      'Microsoft Sans Serif', 'Palatino Linotype', 'Segoe UI', 'Tahoma',
      'Times New Roman', 'Trebuchet MS', 'Verdana',
    ],
    plugins: [
      { name: 'PDF Viewer', filename: 'internal-pdf-viewer', description: 'Portable Document Format' },
      { name: 'Chrome PDF Viewer', filename: 'internal-pdf-viewer', description: 'Portable Document Format' },
      { name: 'Chromium PDF Viewer', filename: 'internal-pdf-viewer', description: 'Portable Document Format' },
      { name: 'Microsoft Edge PDF Viewer', filename: 'internal-pdf-viewer', description: 'Portable Document Format' },
      { name: 'WebKit built-in PDF', filename: 'internal-pdf-viewer', description: 'Portable Document Format' },
    ],
  },
  {
    name: 'macOS Desktop',
    platform: 'MacIntel',
    uaPlatformToken: 'Macintosh; Intel Mac OS X 10_15_7',
    clientHintsPlatform: 'macOS',
    platformVersion: '14.5.0',
    arch: 'arm',
    bitness: '64',
    maxTouchPoints: 0,
    taskbarHeight: 25,
    dpr: 2,
    chromeVersions: [
      '132.0.6834.110',
      '131.0.6778.205',
      '130.0.6723.117',
      '133.0.6943.54',
      '134.0.7025.40',
    ],
    hardwareConcurrency: [8, 10, 12],
    deviceMemory: [8, 16],
    screenResolutions: [
      [1440, 900],
      [1680, 1050],
      [2560, 1600],
      [1920, 1200],
    ],
    gpus: [
      { vendor: 'Google Inc. (Apple)', renderer: 'ANGLE (Apple, Apple M1, OpenGL 4.1)' },
      { vendor: 'Google Inc. (Apple)', renderer: 'ANGLE (Apple, Apple M2, OpenGL 4.1)' },
      { vendor: 'Google Inc. (Apple)', renderer: 'ANGLE (Apple, Apple M3, OpenGL 4.1)' },
    ],
    languages: [
      { primary: 'zh-CN', list: ['zh-CN', 'zh', 'en-US', 'en'], accept: 'zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7' },
      { primary: 'en-US', list: ['en-US', 'en'], accept: 'en-US,en;q=0.9' },
    ],
    timezones: [
      { name: 'Asia/Shanghai', offset: -480 },
      { name: 'America/Los_Angeles', offset: 480 },
      { name: 'America/New_York', offset: 300 },
    ],
    fonts: [
      'Arial', 'Arial Black', 'Comic Sans MS', 'Courier New', 'Georgia',
      'Helvetica', 'Helvetica Neue', 'Impact', 'Lucida Grande', 'Monaco',
      'Palatino', 'Tahoma', 'Times New Roman', 'Trebuchet MS', 'Verdana',
      'Menlo', 'SF Pro', 'Apple Color Emoji',
    ],
    plugins: [
      { name: 'PDF Viewer', filename: 'internal-pdf-viewer', description: 'Portable Document Format' },
      { name: 'Chrome PDF Viewer', filename: 'internal-pdf-viewer', description: 'Portable Document Format' },
      { name: 'Chromium PDF Viewer', filename: 'internal-pdf-viewer', description: 'Portable Document Format' },
      { name: 'WebKit built-in PDF', filename: 'internal-pdf-viewer', description: 'Portable Document Format' },
    ],
  },
  {
    name: 'Linux Desktop',
    platform: 'Linux x86_64',
    uaPlatformToken: 'X11; Linux x86_64',
    clientHintsPlatform: 'Linux',
    platformVersion: '6.5.0',
    arch: 'x86',
    bitness: '64',
    maxTouchPoints: 0,
    taskbarHeight: 30,
    dpr: 1,
    chromeVersions: [
      '132.0.6834.110',
      '131.0.6778.205',
      '130.0.6723.117',
      '133.0.6943.54',
    ],
    hardwareConcurrency: [4, 8, 16],
    deviceMemory: [4, 8, 16],
    screenResolutions: [
      [1920, 1080],
      [2560, 1440],
      [1366, 768],
    ],
    gpus: [
      { vendor: 'Google Inc. (NVIDIA Corporation)', renderer: 'ANGLE (NVIDIA Corporation, NVIDIA GeForce RTX 3070/PCIe/SSE2, OpenGL 4.5)' },
      { vendor: 'Google Inc. (Intel)', renderer: 'ANGLE (Intel, Mesa Intel(R) UHD Graphics 630 (CFL GT2), OpenGL 4.6)' },
      { vendor: 'Google Inc. (AMD)', renderer: 'ANGLE (AMD, AMD Radeon RX 6700 XT, OpenGL 4.6)' },
    ],
    languages: [
      { primary: 'en-US', list: ['en-US', 'en'], accept: 'en-US,en;q=0.9' },
      { primary: 'zh-CN', list: ['zh-CN', 'zh', 'en-US', 'en'], accept: 'zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7' },
    ],
    timezones: [
      { name: 'America/New_York', offset: 300 },
      { name: 'Asia/Shanghai', offset: -480 },
      { name: 'Europe/Berlin', offset: -60 },
    ],
    fonts: [
      'Arial', 'Courier New', 'DejaVu Sans', 'DejaVu Serif', 'DejaVu Sans Mono',
      'Droid Sans', 'FreeSans', 'Liberation Mono', 'Liberation Sans',
      'Liberation Serif', 'Noto Sans', 'Noto Serif', 'Ubuntu', 'Ubuntu Mono',
    ],
    plugins: [
      { name: 'PDF Viewer', filename: 'internal-pdf-viewer', description: 'Portable Document Format' },
      { name: 'Chrome PDF Viewer', filename: 'internal-pdf-viewer', description: 'Portable Document Format' },
      { name: 'Chromium PDF Viewer', filename: 'internal-pdf-viewer', description: 'Portable Document Format' },
    ],
  },
];

module.exports = { PRESETS };
